[package]
name = "model_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
relative-path = { version = "1.9.3", features = ["serde"] }
log = "0.4"
env_logger = "0.11.8"
