[comfyui]
enabled = true
path = "C:\\Users\\serge\\Documents\\LLMs\\ComfyUI\\models"

[webui]
enabled = true
path = "C:\\Users\\serge\\Documents\\LLMs\\webui_forge_cu124_torch24\\webui\\models"

[general]
path = "C:\\Users\\serge\\Documents\\LLMs\\Models"
